[package]
name = "instruct-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.syn]
version = "1.0"
features = ["full"]

[dependencies.quote]
version = "1.0"

[lib]
proc-macro = true
