[package]
name = "instructor"
version = "0.1.0"
edition = "2021"

[dependencies]
openai-api-rs = "4.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
instruct-macros = { path = "../instruct-macros" }

[[bin]]
name = "main"
path = "src/main.rs"
